### ISSUE TITLE
boost button looking blurry

### ISSUE THREAD

**Issue by fullpwn** [ronilaukkarinen/mastodon-bird-ui#102]
<img width="1165" alt="image" src="https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/57821130/77e92bae-44ff-4380-a2ca-918565d394d5">

**Comment by ronilaukkarinen** [comment]
Currently impossible to fix without rewriting it completely. It is an image based animation and I’m right now not willing to draw it myself as SVG animation.
