### ISSUE TITLE
Bluesky icon is just a square

### ISSUE THREAD

**Issue by dhelonious** [ronilaukkarinen/mastodon-bird-ui#105]
I think the Bluesky icon should contain a butterfly, but currently it is just a square with rounded corners:

data:image/svg+xml, %3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 448 512' width='18' height='18'%3E%3Cpath fill='%23717c9b' d='M400 32H48C21.5 32 0 53.5 0 80v352c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48V80c0-26.5-21.5-48-48-48z'%3E%3C/path%3E%3C/svg%3E

Since I could not find an svg image, I made a quick bitmap tracing that could be used as a placeholder:

data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 8.467 8.467' width='32' height='32'%3E%3Cpath fill='%23717c9b' d='M67.256 111.972c-.545-.648-.629-.916-.411-1.323.15-.28.477-.52.727-.531.289-.013.204-.113-.236-.274-.862-.316-1.295-1.239-1.295-2.76 0-1.071.058-1.179.643-1.179.65 0 2.043 1.149 2.88 2.374l.446.655.446-.655c.837-1.225 2.23-2.373 2.88-2.373.584 0 .642.107.642 1.178 0 1.528-.435 2.45-1.295 2.74-.686.23-.686.233-.094.424.787.253.78 1.214-.017 1.961-.893.84-1.748.751-2.114-.218-.165-.437-.364-.794-.442-.794-.078 0-.3.357-.493.794-.47 1.06-1.365 1.053-2.267-.02z' transform='translate(-65.776 -105.112)'/%3E%3C/svg%3E

**Comment by ronilaukkarinen** [comment]
That was before they had the butterfly brand. You could send a PR about this while you're at it? I'll implement it during the upcoming weekend or weekend after that.
