### ISSUE TITLE
Issue: Verified URL in Bio causes Line Break

### ISSUE THREAD

**Issue by Shanesan** [ronilaukkarinen/mastodon-bird-ui#107]
Version: 1.84 using [Layout-Single-Column](https://github.com/ronilaukkarinen/mastodon-bird-ui/blob/main/layout-single-column.css), copied and pasted into `admin/settings/appearance`

Issue: Verified check-mark on a user's bio causes the URL to be line-broken.

Example: https://mastodon.tails.ch/@shanie

<img width="257" alt="Screenshot 2024-02-09 at 4 23 41 PM" src="https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/22644226/f0a94fbe-26e1-4bad-8b2a-7a58b327320d">

I see it doesn't happen on https://mementomori.social/@rolle but I'm also noticing the checkmarks are very different.

**Comment by Shanesan** [comment]
I see it doesn't happen on https://mementomori.social/@rolle but I'm also noticing the checkmarks are very different.

**Comment by ronilaukkarinen** [comment]
I don't see that in there.

![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/13e4d4ef-efd6-470d-b248-7e6c641a6057)

That doesn't look right, and doesn't look like Mastodon Bird UI issue. The CSS has been modified there and I don't exactly what's been done. Going to close this issue.

**Comment by Shanesan** [comment]
```
.app-body.theme-default.no-reduce-motion.layout-single-column {
background: linear-gradient(180deg, #0b202a, #0b202a, #0b202a, #0b202a, #1e3b51) repeat fixed top left;
}
```

Was added to the top of the CSS to create the colored background. Turns out it was likely previously cached CSS which was causing the issue (even after force-refreshing) so it looks like it is fine. Thanks for verifying!
