### ISSUE TITLE
New Default Icons Not Replaced (mastodon.social)

### ISSUE THREAD

**Issue by elliothco** [ronilaukkarinen/mastodon-bird-ui#109]
I'm on the mastodon.social server (which is currently on version v4.3.0-nightly.2024-02-17-security) so these changes will probably be coming in the next major release of mastodon. On this version, there are new icon designs which use a new icon library that isn't font awesome. Because of this, the replacements the CSS does to .fa no longer work, so the custom icons to not appear. Another related bug is that the repost icon no longer has the proper coloring when active (the button is active in the screenshot, but appears gray instead of the expected green).

<img width="520" alt="image" src="https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/160373706/c1182acc-8e50-4e57-a1d6-457cf08742f4">

**Comment by ronilaukkarinen** [comment]
Please use the nightly branch for nightly Mastodon version. Stable won't work with that.
