### ISSUE TITLE
Not compatible with Mastodon's version 4.3.0-nightly.2024-02-23

### ISSUE THREAD

**Issue by expertmanofficial** [ronilaukkarinen/mastodon-bird-ui#110]
![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/119038242/b30a3425-11a9-4897-ac21-b59f955e4581)

# To reproduce:

**Step 1.** Use [Waterfox](https://waterfox.net) browser and if possible, use Linux Mint 20.3, Cinnamon (because that's the OS I use).
**Step 2.** Have Stylus extension installed and add MBUI's css to modify mastodon.social.
**Step 3.** With your mastodon.social account, open mastodon.social/home.
**Step 4.** Now by idea, you should have the same result as I do (see screenshot).

**Comment by ronilaukkarinen** [comment]
Probably not, as my server and tests are still in 2024-02-16.

Mastodon Bird UI is also not compatible with version 2025-04-05 and 2026-06-02. It is not even compatible with 4.3.0 stable as we are not there yet. No reason to open a new issue for these, we’ll get there eventually.

**Comment by ronilaukkarinen** [comment]
Seems to work just fine. Did you use the nightly version or stable? Nightly works with main. Tested with the version today.

![mementomori test_home (6)](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/dd608de4-301c-4b27-a1e3-49d3266f44d5)

**Comment by expertmanofficial** [comment]
it doesn't works with mastodon.social specifically, via Stylus.

**Comment by expertmanofficial** [comment]
i used stable version.

**Comment by ronilaukkarinen** [comment]
> i used stable version.

Mastodon Bird UI stable (main) is not compatible with Mastodon nightly (main). Please use the [nightly branch](https://github.com/ronilaukkarinen/mastodon-bird-ui/tree/nightly) for that.

**Mastodon main/nightly:** `nightly`
**Mastodon stable:** `main`
