### ISSUE TITLE
Theme footer sits on top of other elements

### ISSUE THREAD

**Issue by cadusilva** [ronilaukkarinen/mastodon-bird-ui#114]
When not using the advanced web interface, depending on the screen size, content height or windows size, the theme's footer stays on top of other elements, preventing the use of some buttons.

![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/8684263/cd206e5a-023b-46e3-9dc9-3cae3a9d65f6)

This does not happen when using the default Mastodon theme.

**Comment by ronilaukkarinen** [comment]
Can you share the exact viewport where this happens?
