### ISSUE TITLE
Suggestion: in serch results for profiles, use different colored buttons for the "Follow" and "UnFollow" buttons

### ISSUE THREAD

**Issue by Timothyjchambers** [ronilaukkarinen/mastodon-bird-ui#115]
The suggestion is that for the results of a search for profiles, make the color of the buttons "follow" and "unfollow" two different colors to make it more clear at a glance which accounts you already follow (but might choose to "unfollow" - versus accounts that are new to you and you can choose to newly follow. 

Now the view of them all and the similarity of the words "follow" and "unfollow" make it hard at a glance to visually see the difference between the two types of profiles in the results.

Here is how it looks now with a profile search for "marc" --

<img width="631" alt="Screenshot 2024-03-23 at 10 50 05 PM" src="https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/653520/a7424278-0dd5-4aa6-9c77-ec6448484942">

**Comment by ronilaukkarinen** [comment]
Good suggestion. Before they were icons and as you probably remember we had it like [this](https://github.com/ronilaukkarinen/mastodon-bird-ui/issues/34#issuecomment-1595246111).

However, when they changed to the buttons, those icon classes disappeared. We have absolutely no way to get follow/unfollow states from these buttons, they are just `.button`. Would need at least `.button__unfollow` or something like that. There is no way to catch those conditionally by using text in the button and even if there would, localization would ruin this as you'd have to go through all languages for simple styles. This is why they cannot be styled differently right now, needs a class in the core.

![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/58b9119e-8d71-4014-a5e0-e4eed928ebc6)

**Comment by Timothyjchambers** [comment]
Maybe we make this a recommendation to the Mastodon github... Thanks
