### ISSUE TITLE
Mascot is missing from advanced view

### ISSUE THREAD

**Issue by shleeable** [ronilaukkarinen/mastodon-bird-ui#119]
The mascot is visbile in the default theme, but it missing from the birdui

Before
![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/17537000/4390230e-8158-4cd7-9603-c37211b221b7)

After
![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/17537000/f6d3c2f2-ec86-4507-82cb-75fb185f145d)

**Comment by ronilaukkarinen** [comment]
This is actually a choice, because couldn't get it to work otherwise.

**Comment by shleeable** [comment]
RIP
