### ISSUE TITLE
Readme links to old version of CSS

### ISSUE THREAD

**Issue by mackuba** [ronilaukkarinen/mastodon-bird-ui#121]
I was wondering why the posts in threads aren't displaying correctly… until I realized I had a very old version of the stylesheet added.

I followed the link from the readme, where it says:

> 2. Copy the contents of [layout-single-column.css](https://github.com/ronilaukkarinen/mastodon-bird-ui/blob/master/layout-single-column.css) and [layout-multiple-columns.css](https://github.com/ronilaukkarinen/mastodon-bird-ui/blob/master/layout-multiple-columns.css)

However, these links are linking to the `master` branch, which is apparently an existing branch that's different from the `main` branch which is set as the default, and that branch points to a very old version…

**Comment by ronilaukkarinen** [comment]
Can you send a PR? Will fix in some point, but right now I'm a bit overloaded with other projects.
