### ISSUE TITLE
No recent tagged releases

### ISSUE THREAD

**Issue by jippi** [ronilaukkarinen/mastodon-bird-ui#122]
Hey,

 2.0.0rc12 is the last tagged release, but looks like nightly has rc37? (https://github.com/ronilaukkarinen/mastodon-bird-ui/commit/f15d0b1c81d259dbad831eda765945cf419b8f01)

Do you plan to tag these or have you moved to just a branch instead?

I'm fine either way, just want to adjust my scripts and automations, that haven't updated since rc12 due to no new tags being made

**Comment by ronilaukkarinen** [comment]
Yeah, no release for each tiny rc patch. The newest one can always be found from the [nightly](https://github.com/ronilaukkarinen/mastodon-bird-ui/tree/nightly) branch.

**Comment by jippi** [comment]
alright, I'll adjust my scripts :)
