### ISSUE TITLE
Make media without alt text stand out.

### ISSUE THREAD

**Issue by itspluxstahre** [ronilaukkarinen/mastodon-bird-ui#124]
I want to make any content I boost as accessible as possible. 
How about adding something like the css (but actually make it work fully) to add an outline to media that misses accessible to make it easier not to miss and accidentally bost it. 

I'm sure that someone that actually knows CSS can make it look right and pretty and work in both dark and light modes properly. 

```
.media-gallery__item-thumbnail img:not([alt]),
.audio-player__canvas:not([title]),
.video-player video:not([title]), 
.media-gallery__gifv video:not([title]),
.media-gallery__item-thumbnail img[alt=""], .audio-player__canvas[title=""], .video-player video[title=""], .media-gallery__gifv video[title=""] {
    border: dotted 4px var(--color-red-75) !important;
    padding: 4px !important;
    margin: 4px !important;
    box-sizing: border-box !important; 
}
```

**Comment by ronilaukkarinen** [comment]
Actually experimented with things like this [in the past](https://mementomori.social/@rolle/110011408252142009). But I won't make it default.

Feel free to make your own version though.

**Comment by p37307** [comment]
Glad you didn't make blur a default feature. There's more than one accessibility issue out there. I get that Alt-Text is useful to a segment of the population but what about those people with issues like Parkinson's and other issues that can't readily use existing tools to include alt-text (within the upload dialog?)

Yes, they do exist. Personally affected by this and personally insulted when times I don't have the ability to use the upload dialog to add alt-text and people scream, often without looking at the next post in the thread has alt-text for the image or the request for alt-text.

Must users really be bullied.  There's one particular app that points out that an image doesn't have alt-text in posts and it always seems to be those users screaming about it to me the RARE times my Parkinson's makes adding alt-text within the upload dialog impossible.
