### ISSUE TITLE
Elements of the notifications tab are crushed and/or overlapping.

### ISSUE THREAD

**Issue by BRBWaffles** [ronilaukkarinen/mastodon-bird-ui#129]
I'm guessing this is not intended behaviour. Not sure if the issue is unique to my instance (the-nutrivore.social). Any tips?

![image](https://github.com/user-attachments/assets/ecb55d44-7f49-480a-81cc-4972d3b02cb6)

**Comment by ronilaukkarinen** [comment]
Looks like you are using wrong version for your Mastodon. If you're using Mastodon v4.2.0 or older, you need to use Mastodon Bird UI stable (1.8.5). If you're using Mastodon nightly version (4.3.0 alpha-beta), you need to use Mastodon Bird UI nightly version (2.0.0rc).
