### ISSUE TITLE
Dark square behind rounded avatar

### ISSUE THREAD

**Issue by cadusilva** [ronilaukkarinen/mastodon-bird-ui#131]
I guess this is caused by something related to [mastodon/#31966](https://github.com/mastodon/mastodon/pull/31966). But in the light mode, there's now a dark square behind the round avatar.

![image](https://github.com/user-attachments/assets/56d2cf01-a845-490a-b0fe-a967ec4cb4e2)

Affects: bolha.one, ursal.zone
Mastodon 4.3-beta2

**Comment by ronilaukkarinen** [comment]
Thank you for spotting this. It seems something happened with the structure indeed and border-radius doesn't cut the whole profile image for some reason. A simple border-radius: 50% should do it in the correct element but at the moment I don't have a minute to look at it. Will fix later on, PRs always welcome.
