### ISSUE TITLE
 Big empty space on right

### ISSUE THREAD

**Issue by rsholmes** [ronilaukkarinen/mastodon-bird-ui#133]
There is a big empty space on the right of the standard web interface, below the text input box and above the instance and Mastodon info. It's too big.

![image](https://github.com/user-attachments/assets/8f2982ef-799a-4cf9-9729-3bc95de66312)

The problem is, I have to maximize my browser window if I want to see the Mastodon information below the instance information. Otherwise that information is cut off, and you can't scroll down to it. Naive users might not even realize there is anything down there.

**Comment by ronilaukkarinen** [comment]
I'm not sure exactly what the problem is. this is expected in certain viewports.

<img width="1480" alt="image" src="https://github.com/user-attachments/assets/c1e0d31b-3505-4987-a23a-67953a542562">

Lower screen:

<img width="1480" alt="image" src="https://github.com/user-attachments/assets/52ec3ca3-a9c9-48a8-b349-771c8bff99ac">

What version is your Mastodon?
What version is the Bird UI in use?

**Comment by rsholmes** [comment]
I said what the problem is: In order to see the information at the bottom (the Mastodon version number you asked for, for instance), I have to maximize my browser window. At any smaller size that information is off the bottom of the window, and *cannot be brought into view by scrolling*. If I had a huge resolution monitor that might not be the case; mine is 1920x1080. With the browser window maximized the Mastodon information is just barely within view:

![image](https://github.com/user-attachments/assets/522f37a5-5ae5-41f2-ab46-77b1de0f7a02)

A smaller gap would make the Mastodon information visible without having to alter the window size.

Incidentally I just noticed how `Lists` is not properly placed here.

Mastodon version is v4.3.0-beta.2+pr-32117+io. I do not know which version of Bird the admin has installed.

**Comment by ronilaukkarinen** [comment]
Found the issue now, thanks. The min-height of the `.layout-single-column .columns-area__panels__pane--compositional` is set too high. I'll fix this to the next version, thanks.

![mementomori social_home](https://github.com/user-attachments/assets/68dcd29a-1eda-45f4-ad36-80d5a630de6d)
