### ISSUE TITLE
List icon shakes uncontrollably when clicked and posts margins are too long before click in

### ISSUE THREAD

**Issue by phillycodehound** [ronilaukkarinen/mastodon-bird-ui#135]
List icon shakes uncontrollably when clicked and posts margins are too long before click in. I can provide pictures if you don't see these on your site.

**Comment by phillycodehound** [comment]
Might be Vivaldi. Only happening there.

**Comment by ronilaukkarinen** [comment]
Haven't encountered this. Video screencap appreciated.
