### ISSUE TITLE
Imageless article cards don't display correctly

### ISSUE THREAD

**Issue by AlternateRT** [ronilaukkarinen/mastodon-bird-ui#137]
While using the theme I encountered a few posts with imageless article cards [like the following](https://isfeeling.social/@matt/113317102031466326) and noticed they didn't look quite right:
<img width="619" alt="Screenshot 2024-10-16 at 16 56 31" src="https://github.com/user-attachments/assets/91212d83-d549-4401-a3d5-4fe67ccf62de">

It seems to me like this is caused by the following CSS:
```css
.layout-single-column .status-card:has(.icon-file-text) {
    display: none;
}
```

----
I'm not sure if that particular rule is used anywhere else, but when I removed it, the card looked more correct (and I presume this is how all imageless article cards are actually supposed to look like):
<img width="619" alt="Screenshot 2024-10-16 at 16 56 45" src="https://github.com/user-attachments/assets/129e3150-590f-4a13-b8ca-592986e19b49">

**Comment by ronilaukkarinen** [comment]
Thanks. I think it was added due to [this issue](https://github.com/mastodon/mastodon/issues/26202). I'll fix this in some point. Pull requests always welcome.
