### ISSUE TITLE
Images too narrow

### ISSUE THREAD

**Issue by DismalShadowX** [ronilaukkarinen/mastodon-bird-ui#139]
All images are almost too narrow instead of their full ratio size.

Default Mastodon theme

![Screenshot_20241022-194200.png](https://github.com/user-attachments/assets/4ccfb010-66c8-4055-8c4d-5c509b07cb6c)

This is with BirdUI

![Screenshot_20241022-194231.png](https://github.com/user-attachments/assets/c8e891c5-2835-4d12-95db-aa8d6047678a)

Also, images appeared to be aligned right and not centered

Nightly build.

**Comment by ronilaukkarinen** [comment]
It's a [concious design choice](https://mementomori.social/@rolle/111715873154372109).
