### ISSUE TITLE
Character counter indicator does not change color when char limit is reached/exceeded

### ISSUE THREAD

**Issue by kde3kko** [ronilaukkarinen/mastodon-bird-ui#14]
When using default Mastodon stylesheet, if a user writes too many characters inside the compose form, the counter becomes red by applying the `character-counter--over` class.

<img width="254" alt="char counter with default mastodon style" src="https://user-images.githubusercontent.com/2643961/230748663-0937489c-e29d-48f1-8f01-4608925ec013.png">

The theme right know ignores the applied class and keeps styling the counter color with `--color-dim`.

<img width="314" alt="char counter with Bird UI" src="https://user-images.githubusercontent.com/2643961/230748653-8c0d4c03-c4ca-47d3-9217-99d9a86bba33.png">

I don't know if it's intentional, IMHO the theme should understand the applied class and use the appropriate token to colorize the counter (perhaps `--color-destructive`?)

**Comment by ronilaukkarinen** [comment]
@kde3kko Thanks! Haha I have 10000 characters limit so I never encountered this. Thanks for spotting it!
