### ISSUE TITLE
CSS syntax error: trailing comma in selector

### ISSUE THREAD

**Issue by thomas-pike** [ronilaukkarinen/mastodon-bird-ui#141]
These lines have an erroneous trailing comma in the CSS selector:

* https://github.com/ronilaukkarinen/mastodon-bird-ui/blob/12c1bc1b062fd4e82951dfd4031c45f71c1431a5/layout-multiple-columns.css#L1675
* https://github.com/ronilaukkarinen/mastodon-bird-ui/blob/12c1bc1b062fd4e82951dfd4031c45f71c1431a5/layout-single-column.css#L1732

**Comment by ronilaukkarinen** [comment]
Thanks for spotting! Hmm, I wonder how the CI missed this? While you're at it, can you send a PR? I'll look this over the weekend if I have time.

**Comment by ronilaukkarinen** [comment]
Just noticed the stylelint automations didn't spot this... [issue for reference](https://github.com/stylelint/stylelint/issues/3053).

Going to add more unit tests with alternative plugins.
