### ISSUE TITLE
Cramped menubar in small landscape sizes

### ISSUE THREAD

**Issue by gelbphoenix** [ronilaukkarinen/mastodon-bird-ui#144]
On smaller landscape sized screens the left menubar is a bit cramped and that feels a bit "full".

![image](https://github.com/user-attachments/assets/73a2bcb0-5ed9-473c-8e49-1619f49f7986)

**Comment by ronilaukkarinen** [comment]
There should be improvements to this.

Which version are you running?
What is the viewport exactly in your screenshot? 

![mementomori social_@rolle](https://github.com/user-attachments/assets/5c74c1c5-f99e-404a-aa4f-243647e0ab85)

**Comment by gelbphoenix** [comment]
Using (or - for the moment - better said used) v2.0.6rc3.

Viewport is 1236x781px.

**Comment by ronilaukkarinen** [comment]
Can't replicate this issue on Mastodon v4.4.0-alpha.1. You are using rc-version which is only compatible with Mastodon nightly versions (mainline, alpha, beta, etc.). In the screenshot your Mastodon version is 4.3.1 so you should be using [2.0.5](https://github.com/ronilaukkarinen/mastodon-bird-ui/releases/tag/2.0.5). Unfortunately not all fixes are present there so for the time being you just need to wait until next upgrade or upgrade your instance to the latest nightly.
