### ISSUE TITLE
Top panel opaqueness mismatch in narrow layout

### ISSUE THREAD

**Issue by dhelonious** [ronilaukkarinen/mastodon-bird-ui#145]
On a narrow window, the layout collapses, resulting in a mismatch of opaqueness in the top bar, as shown in this screenshot:

![image](https://github.com/user-attachments/assets/69f76826-2f3d-4b60-bd99-afa9b954f555)

Interestingly, if the window size is even smaller and the sidebar collapses, this problem no longer exists:

![image](https://github.com/user-attachments/assets/269c6db7-01be-4d67-b3c4-21d035d897cf)

**Comment by ronilaukkarinen** [comment]
Can you share the viewport / resolution in pixels?

**Comment by dhelonious** [comment]
This happens when I split the screen of my 14" 1080p work laptop. And I think I'm using an additional 25% scaling. So it should be happening somewhere between 400 and 500 px. I'll check tomorrow.

**Comment by dhelonious** [comment]
This is the point where the right-hand column collapses:

![image](https://github.com/user-attachments/assets/6ce16fc4-4203-40a2-a4de-c5ed0b035427)

![image](https://github.com/user-attachments/assets/c5da63a3-c518-4b87-a93d-c3bd902be45c)

This is where the left sidebar collapses:

![image](https://github.com/user-attachments/assets/14d17289-f874-46d3-a4cb-9434cc4db589)

![image](https://github.com/user-attachments/assets/e4887a4d-73d9-4938-b06f-d3d1e8e2a493)

![image](https://github.com/user-attachments/assets/ec994dfd-d44f-4128-9a91-d468e08f269a)

**Comment by ronilaukkarinen** [comment]
Can't reproduce on v4.4.0-alpha.1 and Mastodon Bird UI 2.0.6rc3.

What is your Mastodon version?
What is your Mastodon Bird UI version?

**Comment by dhelonious** [comment]
I'm running Mastodon v4.3.1 and Bird UI v2.0.4. I will try the latest stable release for Bird UI and otherwise debug my installation. I close this for now.

**Comment by dhelonious** [comment]
I did some digging and found the cause of this problem. Rather than try to explain it here, I made a pull request that shows it.

I'm surprised you can't reproduce this on your instance. But maybe Mastodon 4.4 has changed something about the `tabs-bar__wrapper`?

**Comment by ronilaukkarinen** [comment]
I made a lot of fixes to navigation weeks ago in nightly, the same structural changes seem to have arrived to Mastodon 4.3.2. Version 2.0.6 I just released should fix these issues. I was not able to reliable reproduce this with Mastodon 4.4.0-alpha.1 or Mastodon 4.3.2, with Bird UI versions 2.0.5, 2.0.6rc or 2.0.6.
