### ISSUE TITLE
Firefox -  part of the central column right border is hidden by the compose form gradient

### ISSUE THREAD

**Issue by kde3kko** [ronilaukkarinen/mastodon-bird-ui#17]
On desktop Firefox (111) the gradient used as background for `.compose-form__publish::after` hides part of the adjacent border exactly by 1 px (which is the border width)
<img alt="firefox is missing part of right border" src="https://user-images.githubusercontent.com/2643961/230786107-f68cdaa3-84fe-4076-8519-32f0f5318685.png" width="300"/>

This does not happen on desktop Chrome/ium, didn't have a chance to test on Safari yet.

**Comment by ronilaukkarinen** [comment]
Thanks for spotting. The pseudo might be unnecessary anyway, because I changed the compose form not to resize too much after all, because a user with a disability reported that it went under on screen keyboard. So the whole pseudo should be removed. I'll work on this tomorrow. 👍
