### ISSUE TITLE
Navigation panel height/scroll 

### ISSUE THREAD

**Issue by kde3kko** [ronilaukkarinen/mastodon-bird-ui#18]
This is not really an issue, more a point of discussion, but I don't know where else to put it.
I thought about it a little, and came to no conclusion so here I just document my thoughts.

As it is, the theme renders the sidebar items exactly like Twitter's regarding size and gap between them, and the look and feel is very "familiar".

This is good but, combined with their number (which is higher than Twitter's, 10 vs 8) and the presence of the "trending" graphs right below, creates an overflow/scroll.
I get that ~~the theme is trying to mitigate this by hiding the 3rd trend graph~~ edit: this is not the theme, it's Mastodon's `components.scss` (ouch!), but on my 13'' MB I still need to scroll to see the 2 remaining topics (with scroll=0 i only see the section title and, barely, the first one)

<img width="375" alt="sidebar without scrolling" src="https://user-images.githubusercontent.com/2643961/230951196-90b0282d-e6c4-44c8-88c4-4784ac3cbcf6.png">
<img width="375" alt="sidebar scrolled to reveal trending topics" src="https://user-images.githubusercontent.com/2643961/230951296-e423c285-deb8-4996-8eaa-98f21e923027.png">

To me it feels weird to both:
- ~~hide one of the trending topics in order to make navigation links more prominent~~
- having to scroll to see the full trending section (which, I believe, should be important in a microblogging app, and Twitter itself uses the full right column for this).

This is something highly related (and limited by) how the DOM is organized, and currently I see no clean solution other than reducing a bit the font-size/gap between the navigation panel items.

**Comment by ronilaukkarinen** [comment]
I don't really see a problem in this since it's really an edge case like you said, on small screen devices.

>  I see no clean solution other than reducing a bit the font-size/gap between the navigation panel items

This is not an option, I like the white space.

So we go with scrolling down when needed this time.
