### ISSUE TITLE
When opening the Media item in the profile menu, the button to browse posts is not visible.

### ISSUE THREAD

**Issue by fofwisdom** [ronilaukkarinen/mastodon-bird-ui#21]
Original
![image](https://user-images.githubusercontent.com/205521/233068162-700dd752-5ab0-47bb-bd7a-7ac248e60294.png)

MBU
![image](https://user-images.githubusercontent.com/205521/233068373-f6c3c0f7-1f1c-48ea-9c1a-c3109a1f7025.png)

**Comment by ronilaukkarinen** [comment]
This is intended, for me they were a distraction and wanted it to look like more minimal. You can show them by removing [this](https://github.com/ronilaukkarinen/mastodon-bird-ui/blob/e6d84e8d82ff5514a3e34b56342e893ac12f06d4/style.css#L340-L343) or forcing display block with !imporant at the end of your Custom CSS.

**Comment by fofwisdom** [comment]
Thanks to your friendly guide, I'm tweaking it well every time.
