### ISSUE TITLE
Server Rules Not Visible During Report

### ISSUE THREAD

**Issue by tommertron** [ronilaukkarinen/mastodon-bird-ui#3]
Tested on Safari Version 15.5 (17613.2.7.1.8), MACOs 12.4 (21F79)

Example:
![image](https://user-images.githubusercontent.com/7305405/227243694-05df2a39-e957-45fd-8a44-03c3836f61bb.png)

**Comment by ronilaukkarinen** [comment]
Thanks, I'll fix it soon.
