### ISSUE TITLE
Ellipse shaped counter with 10+ notifications

### ISSUE THREAD

**Issue by davidpmccormick** [ronilaukkarinen/mastodon-bird-ui#32]
I’m assuming that this should be a circle regardless of the number of notifications (but haven’t looked at Twitter for the longest time so perhaps this is intentional and sorry if this issue is a waste of time)

![IMG_4123](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1394592/106e9ef0-4e3a-4d7c-a280-f53fb27bbf49)

**Comment by ronilaukkarinen** [comment]
The number doesn't fit there with a circle. It's the same thing with Twitter and others, not circular:

![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/cef0129f-2fed-4b92-b96f-83c7d71087c3)

**Comment by davidpmccormick** [comment]
Fair dos. It's more a pill than an ellipse when there's more than one character though.

**Comment by ronilaukkarinen** [comment]
From [this post](https://mementomori.social/@mikey@neovibe.app/110667311524475623):

> [@mikey](https://mementomori.social/@mikey@neovibe.app) This has been answered earlier, can't remember where though so I'm answering here:
>
> Not possible to do otherwise CSS-only. I'm sure you agree this doesn't look good either (pictured below).
> 
> The styles cannot be changed conditionally based on how much notifications there is. Twitter has it similarly in back-end so that the radius changes to not so round version when the notifications reach two or more numbers.
> 
> So it is what it is and I'll take it.

**Comment by davidpmccormick** [comment]
If the `border-radius` in `px` (or `rem`, or another fixed unit) rather than `%` I think the ellipse would become a pill

**Comment by ronilaukkarinen** [comment]
> If the `border-radius` was set in `px` (or `rem`, or another fixed unit) rather than `%` I think the ellipse would become a pill

Good point, but it might not be able to get it fully round when the number has one digit. So it's either-or. Have to experiment on this later. Feel free to send a PR with examples.

**Comment by davidpmccormick** [comment]
Looking again, I think the fact there's more horizontal padding (`6px`) than vertical (`1px`) means that `border-radius: 50%` already equates to a slight capsule shape even for a single character. To my mind a slight pill would be preferable (but I realise this is hugely subjective).
