### ISSUE TITLE
Swiping bottom bar triggers multi-tasking on some phones

### ISSUE THREAD

**Issue by ronilaukkarinen** [ronilaukkarinen/mastodon-bird-ui#33]
As reported by @mstdn:

> No rush! But I wanna let you know that on ‘bigger’ iPhones we have a little issue with the bottom menu. Since swiping there triggers the multi tasking.
>
> Maybe something for a future update somewhere 🤗
> 
> ![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/0e0770a9-9877-4bc6-844e-04c43d619cf5)

**Comment by ronilaukkarinen** [comment]
While improving this it would be perhaps wise to re-think this overall, related: #26. Any help appreaciated, be it code or ideas.

**Comment by mstdn** [comment]
> While improving this it would be perhaps wise to re-think this overall, related: #26. Any help appreaciated, be it code or ideas.

I think this would be wise haha! Maybe stick with 3/4 buttons and a "more" or something like that? 💭

**Comment by ronilaukkarinen** [comment]
Good idea, added the thought to #26.

As for this particular issue I have no ideas on how to fix it. I do have gestures enabled on my phone but I don't have that bar visible. If I swipe too low, I will get the gesture activated, but I've learned to swipe just enough on top of it that it doesn't matter.

I'd rather not add extra black bar on mobile. This kinda depends on a mobile phone setting rather than the theme.

Ideas welcome.

**Comment by ronilaukkarinen** [comment]
> This might be what you are looking for, I don't have an iphone so sadly can't test it myself https://css-tricks.com/css-fix-for-100vh-in-mobile-webkit/
> 
> ```css
> body {
>   min-height: 100vh;
>   min-height: -webkit-fill-available;
> }
> html {
>   height: -webkit-fill-available;
> }
> ```
> 
> This mentions a footer, but it _should?_ also behave similarly with a `bottom: 0;` element

Thanks, I'll test it out soon-ish!

**Comment by ronilaukkarinen** [comment]
Fixed in #72.
