### ISSUE TITLE
For Lists, Can we Make the Checkmarks More Clear

### ISSUE THREAD

**Issue by Timothyjchambers** [ronilaukkarinen/mastodon-bird-ui#34]
For adding and removing users from the Lists, a suggestion to make the lists green when the users is IN the list, and a red X mark to remove them?

 Or some other visual solution to make it more clear at a glance which lists the account is currently in, and which they are not?
 
 The visual similarity of the X and the + in the current UI and that they are all the same color make this bit of Mastodon UI very hard visually to tell who is in what list at a first view.

<img width="381" alt="Screenshot 2023-06-14 at 8 53 21 PM" src="https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/653520/b02058ef-a493-4501-b4b9-9945b74791fd">

**Comment by Timothyjchambers** [comment]
You could use a simliar UI to what is here in the BirdUI: Where the chosen UI elements are green but mouse over red to show you are about to unselect them.
<img width="635" alt="Screenshot 2023-06-16 at 4 06 39 PM" src="https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/653520/fdaf5103-40d0-42d4-b727-9516e6f35b35">

**Comment by ronilaukkarinen** [comment]
Good point. I actually used a lot of effort having those follow/unfollow colors and icons properly set up because in original Mastodon UI they were not clear enough. For lists I haven't yet focused on that much, they are right now from the original Mastodon UI.

This is low priority for me, but I'll try and improve them when I have time. Contributions always welcome. :)

**Comment by itbeard** [comment]
> 

Do you mean smtg like that?
![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/45439635/45987704-f4ac-4a04-80e1-9cd6bbdaca40)

**Comment by Timothyjchambers** [comment]
Yes!

**Comment by ronilaukkarinen** [comment]
I'm going to use the same logic here than in follows of (Mastodon stable version. On the nightly/upcoming version follow icons have been replaced by button):

![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/106b3617-1f4a-4084-86ef-5c1f5759b0fb)

Hover:

![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/86039149-ec4b-4c5c-adcd-20f116aa5285)
