### ISSUE TITLE
Profile Links Obscured by UI

### ISSUE THREAD

**Issue by nightpaws** [ronilaukkarinen/mastodon-bird-ui#35]
The birdsite only supported a single profile link, whereas up to 4 can be included here. This means the second link is often crunched and further links are unreadable, e.g.

![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/5623474/1d7bffe8-c795-4b4b-b91f-f2aeb929dfcf)

Not sure how this could elegantly be added with CSS, but it would be nice to be able to see that information.

**Comment by ronilaukkarinen** [comment]
Long links are a bit problematic, the official truncates them as well and I have no issue with that.

I have many links and it looks fine to me!

![Screen-Shot-2023-06-28-10-04-59 97](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/1ab6844e-c4bc-4c24-8551-d8884c6ff401)

**Comment by nightpaws** [comment]
Hmm. I'm unable to replicate the above using firefox @ronilaukkarinen - could you confirm which browser you're using to see multiple rows of links?

**Comment by Alex0007** [comment]
What if i'm not using these fields for links?
But instead for text labels (where left part also meaningful)

<img width="425" alt="Screenshot 2023-07-04 at 18 25 18" src="https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1143226/2530412e-dedf-43f8-a4b8-531ed1e1ac91">
<img width="566" alt="Screenshot 2023-07-04 at 18 25 30" src="https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1143226/5d090c2c-150f-4439-8fab-03ace4b077ae">
