### ISSUE TITLE
Bug on notifications and comments on mastodon 4.1.2 nightly

### ISSUE THREAD

**Issue by uandreew** [ronilaukkarinen/mastodon-bird-ui#36]
https://github.com/mstdn/Bird-UI-Theme-Admins/issues/4

**Comment by ronilaukkarinen** [comment]
You are using mastodon nightly/main, right? Based on those lines that seems to be the case. It's not yet supported, only stable 4.1.2 has full support. Lucky for you [I'm working on it](https://github.com/ronilaukkarinen/mastodon-bird-ui/tree/mastodon-4.1.2-nightly) but as of right now this is a non-issue.

**Comment by uandreew** [comment]
You are right, thank you!

**Comment by ronilaukkarinen** [comment]
To note, it needs a lot more work than that. Lots of UI changes:

![Screenshot from 2023-07-03 00-20-43](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/22f553e4-0ddd-4fd2-a4a2-d1d22cdbad77)
