### ISSUE TITLE
Not working on Mastodon.social using LiveCSS Editor or Stylish

### ISSUE THREAD

**Issue by rolandixor** [ronilaukkarinen/mastodon-bird-ui#41]
I've copied the files as the instructions say, but nothing has changed with either addon.

**Comment by ronilaukkarinen** [comment]
Need a bit more information.

- Do you use advanced interface or single column interface? 
- What file did you use?
- What browser?

**Comment by ronilaukkarinen** [comment]
I'm going to close this for now, let me know the details so I can help!

**Comment by rolandixor** [comment]
* Do you use advanced interface or single column interface?
   Single
* What file did you use?
   The single column css file.
* What browser?
   Firefox

**Comment by ronilaukkarinen** [comment]
I have no idea why it doesn't work for you but works for everybody else.

**Comment by rolandixor** [comment]
I'll try it without any Mastodon related addons and see if it helps.
