### ISSUE TITLE
Image view arrows position

### ISSUE THREAD

**Issue by alxsimon** [ronilaukkarinen/mastodon-bird-ui#42]
Trying the theme on vivaldi on mastodon 4.1.2

When viewing images the arrows are not vertically centered and overlap with the close button.

![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/9567176/9a82797d-cbbd-4c9c-aae0-9a7e5c381722)

![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/9567176/07490fb1-24c4-4ac9-b6bd-3396a190d5da)

**Comment by ronilaukkarinen** [comment]
Hmm, interesting. Does this happen only on advanced interface or on single column as well? You are running Mastodon 4.1.2 stable or main (nightly)? What Mastodon Bird UI version is in use?

**Comment by alxsimon** [comment]
We are running the stable mastodon versioin, and I am using the current master of the UI.
This happens both on advanced and single column.
I run the css through the extension 'User Javascript and CSS'
