### ISSUE TITLE
2 logos in tablet/mobile view on Safari

### ISSUE THREAD

**Issue by misterzwiebel** [ronilaukkarinen/mastodon-bird-ui#44]
There are 2 logos when in tablet or mobile view on Safari.
Happens in Safari 14.1.2 and 15.4 on macOS and Safari 15 on iOS, not sure about the latest versions.

<img width="1280" alt="" src="https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/88088481/c6c960c0-b98f-4dc6-aa5f-4dce5814cf95">

**Comment by ronilaukkarinen** [comment]
Hmm, that's weird. Does it happen only on Safari? Only on mobile or in other views too? I currently have only Macbook, gotta test with it soon.

**Comment by ronilaukkarinen** [comment]
Should be fixed now in 1.6.1 and 1.6.1-nightly.
