### ISSUE TITLE
image zoom doesn't work on android ff

### ISSUE THREAD

**Issue by ikke-t** [ronilaukkarinen/mastodon-bird-ui#51]
If I click on image, the enlargened picture is hard to zoom. And it can't be moved. So in practise impossible to zoom and scroll.

**Comment by ronilaukkarinen** [comment]
Just tested it on default theme on Android on Firefox and it occurs there. I suggest you open an issue on [Mastodon issues](https://github.com/mastodon/mastodon/issues).
