### ISSUE TITLE
RFE: dark mode button to toolbar

### ISSUE THREAD

**Issue by ikke-t** [ronilaukkarinen/mastodon-bird-ui#52]
I rest my eyes in evening by using dark mode, and it would be convenient to have single press button to switch dark mode on/off.

I already asked for the theme to follow android/desktop mode, but I was told it would be too messy to implement and maintain. So how about this sort of a compromize? 😀

**Comment by ronilaukkarinen** [comment]
Cannot be done via CSS only, needs JavaScript. Perhaps in the fork some day, but as I don't personally switch between modes (dark mode always everywhere) I'm not interested in spending time to this right now. Will perhaps look for auto dark/light theme option later...
