### ISSUE TITLE
Audioplayer height in Safari

### ISSUE THREAD

**Issue by misterzwiebel** [ronilaukkarinen/mastodon-bird-ui#53]
<img src="https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/88088481/f78f915f-0f1b-4c8c-81fc-be8315260589">

Not sure whats causing it, but the audio player is missing some height in Safari 14. (Works fine in v15)

**Comment by ronilaukkarinen** [comment]
@misterzwiebel Can you confirm that this is only with Mastodon Bird UI, not with default UI?

**Comment by misterzwiebel** [comment]
Yes, the audio player on the original instance (which has the default Mastodon theme) looked fine.
