### ISSUE TITLE
all errorphant all the time, help

### ISSUE THREAD

**Issue by solarbirdy** [ronilaukkarinen/mastodon-bird-ui#58]
I followed the installation instructions to install birdUI as an optional theme for 4.1.5 (except for the default part, because I don't want it to be default, I want it to be an option) and when I tried switching my account to it, all I get now is the Errorphant and I can't change my theme back. So that's bad.

[e320908c-7550-4a7f-870a-88bd45de8b1c] method=GET path=/ format=html controller=HomeController action=index status=500 error='ActionView::Template::Error: Webpacker can't find mastodon-bird-ui-light.css

I was trying to build and getting compilation failures before this. (This is new behaviour.) These were all issues like this:

ERROR in ./app/javascript/mastodon/features/compose/components/compose_form.js 1:2099
Module parse failed: Unexpected token (1:2099)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.

I don't know why this would start now since I don't see how this is particularly related to a theme, but, well, it has.

Then the backend processes must've restarted, since it suddenly noticed all the missing precompiled resource files, right? And I pulled them back in off backup, and we were fine - and also, the compilation problem vanished. So I restarted all the back-end processes and we came back up clean.

And so I tried switching to the BirdUI style and that's where I am now.

I can get to my account through clients but not the web UI. I mostly just want a way to reset the style associated with my account so I can get back to the web UI. Help?

**Comment by ronilaukkarinen** [comment]
That's strange. Which installation instructions did you follow? If you want it as optional "Elephant" theme, you could use the [instructions by stux](https://github.com/mstdn/Bird-UI-Theme-Admins). That error seems not to relate to Mastodon Bird UI at all. What does that line in compose_form.js look like and why it throws an error? Did you test the modifications locally or directly in production? I'd highly recommend doing this in local first.

**Comment by solarbirdy** [comment]
nope I followed yours, BUT

the problem turned out to be that somehow yarn.lock (which I swear to you I have _never_ touched) had been changed... somehow... at some point... and I have no idea why. and doing a yarn install and all the other normal steps wasn't reverting it. but a manual git revert did and then suddenly hey look compiling!

**Comment by solarbirdy** [comment]
I don't know when this could've happened, all the upgrades I've ever done have gone very smoothly and this is the first time the issue showed up. (but my history in software kind of has that as a running theme? so... I'm not surprised.) It may have been broken for _a while_ and just not actually failing for... some reason. Or other. [insert QI "Nobody knows" banner here]

**Comment by p37307** [comment]
I had a phantom yarn.lock change issue a couple weeks ago and I NEVER touched it. I hadn't even entered Mastodon to anything since a previous update weeks before. I wonder if the OS did something kinky with yarn during an OS update, etc. That's all I can think of.
