### ISSUE TITLE
Install Question.

### ISSUE THREAD

**Issue by MadBloris** [ronilaukkarinen/mastodon-bird-ui#6]
I am probably being incredibly dim here, but CSS isn't my thing (I am more a hardware guy)

"Install it as CSS to your assets"

I don't follow this line. I can install it manually via my browser or the admin panel. But I would like to do it server side from the box itself.

/public/assets/  doesn't seem right.

Could you explain that step (for us simpletons) in a little more detail please? 

I appreciate I am going to look like a right prat now. 

EDIT //

My plan was to work out how to add it as a new theme, if that is at all possible.

**Comment by ronilaukkarinen** [comment]
That part of the instructions are just an example. I have now clarified it README. I have no experience in adding the styles to Mastodon but I believe styles are located at [`app/javascript/styles`](https://github.com/mastodon/mastodon/tree/500d6f93be0f84b7a8d338c8860936618f27dfe8/app/javascript/styles).

The "proper" designed use for this is to add the contents of style.css to the **Custom CSS** section of your instance, located at https://_yourinstanceurl_/admin/settings/appearance:

![Screen-Shot-2023-03-31-13-25-52](https://user-images.githubusercontent.com/1534150/229095651-7ecbb9dd-0a30-4cb2-ae2b-aed99bdd998b.png)

**Comment by MadBloris** [comment]
Cheers for the clarification. I thought I was doing something wrong or not understanding!

**Comment by ronilaukkarinen** [comment]
Nope, I was just being unclear! Thanks for pointing that out. 👍
