### ISSUE TITLE
Re-think profile links/labels

### ISSUE THREAD

**Issue by ronilaukkarinen** [ronilaukkarinen/mastodon-bird-ui#61]
For reference, the original Mastodon UI shows them like this:

![Screen-Shot-2023-08-01-14-42-23 22](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/bd08234d-17a0-4c25-8e85-cbe272ed6ad4)

On the birdsite they are like this:

![Screen-Shot-2023-08-01-14-40-19 78](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/050bba55-b7cf-4d2c-aa83-1883b2d34d29)

On the bird UI like this:

![Screen-Shot-2023-08-01-14-36-31](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/0c7a69c7-9acf-4e05-8c9e-6c02b6155134)

This is a design choice. But what if we have only textual labels or we want to show the labels? 

I really don't like them taking so much space like in the original UI. But need to re-think the presentation if there's text only like [this comment](https://github.com/ronilaukkarinen/mastodon-bird-ui/issues/35#issuecomment-1620347831) suggests.

**Comment by ronilaukkarinen** [comment]
Also pointed out [here](https://mementomori.social/@turkufrontend@tivia.social/110812782324111621) (in Finnish).

**Comment by Freeplayg** [comment]
What about something similar to Elk? 
![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/40742947/ab218135-f708-48af-b482-4141cf7f6cd5)

Even if it takes up a little more space, I still think it fits the style
I wonder if you could also use the title attribute in the `dd` element to look for domains and add the corresponding icons like in the bottom 3, but that may require more work

**Comment by ronilaukkarinen** [comment]
Thanks for the thoughts @Freeplayg, this got me inspired. I have now experimented with this and managed up until this point:

![Screen-Shot-2023-09-13-23-22-00 39](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/c3d210c7-9a98-4cec-a48b-97195be4ec36)

Got it to work so that if link label is "Website", it's hidden. Otherwise the labels with links show up first and YouTube, Twitter/X, Twitch, GitHub show up inlined in the last.

![Screen-Shot-2023-09-13-23-43-41 12](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/06d5f21f-250a-4b11-b1d2-1e9ec38f9fce)

However, things get tricky when links are verified. When multiple links are verified, it looks clumsy with the check icon:

![Screen-Shot-2023-09-13-23-22-40 39](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/5dc1f0fe-40a1-4ac9-bf05-2d8cbe58137d)

I don't like this. Two icons side by side, yuck.

So... I was thinking, if one of the links have been verified, let's not show checkmarks and greens with all of them, why not just check if there is at least one link with verified class and then show a verified badge after the full name:

![Screen-Shot-2023-09-13-23-36-34 55](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/70d77856-5a72-4439-bda9-272c3368d28a)

I'm really not fan of the border around the whole link like the Elk does it. That doesn't tell much about anything and looks strange.

However, this way we don't know which links are verified but does it matter?

Or, we could have the verified icons in all the links:

![Screen-Shot-2023-09-13-23-50-50 25](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/2f0d2469-d929-4ade-8855-602c06185611)

...but I don't know if it works well if the link has a label:

![Screen-Shot-2023-09-13-23-53-54 32](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/7040ec58-1042-462e-b901-f79cde17d394)

## Current disadvantages

Because `:has` is not yet supported on Firefox we'd have to accept things will look like this:

![Screen-Shot-2023-09-13-23-49-57 90](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/5197557c-0129-43d6-9864-3cb031f9986a)

These tests are present shortly in the `dev-profile-links-labels-verified-61` branch.

**Comment by ronilaukkarinen** [comment]
Needs a bit more re-thinking, [ref](https://mementomori.social/@vsaw@mastodon.social/111060205992679440).

**Comment by Freeplayg** [comment]
The replacing the icon w/ verified badge bit would've been enough right ?

**Comment by ronilaukkarinen** [comment]
Alternative style, I think I'll go with this:

![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/a3dc5a00-2589-404f-8051-c4fce1bef00a)

**Comment by fofwisdom** [comment]
Just block is well......
<img width="617" alt="image" src="https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/205521/b8ab2434-bd78-421e-938f-db4242257af6">

https://github.com/NetspherePub/mastodon/blob/3699ccc96039dc20b9ffd56a898495178fc6f591/app/javascript/styles/bird-ui/layout-single-column.css#L2193
