### ISSUE TITLE
Vertical video layout looks better in vanilla

### ISSUE THREAD

**Issue by JustDalek** [ronilaukkarinen/mastodon-bird-ui#62]
Hello! I dont know when the change happened, but some time ago I noticed my videos preview began to look a bit odd on my mastodon instance.

Today I compared against mastodon.social and noticed it is very different

My videos on the vanilla UI fills out a nice frame as seen here
<img width="249" alt="image" src="https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/78516780/fb8c7b95-296e-4894-b438-94e2a290935c">

Whereas on my instance with birdUI, they seem to do this
<img width="398" alt="image" src="https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/78516780/a916a787-f9c4-4284-8786-c27b13f26a68">

The biggest noticeable issue of course is the giant black bars that look gross. Is that something we can change?

**Comment by ronilaukkarinen** [comment]
Can you link to the post in question?

**Comment by JustDalek** [comment]
> Can you link to the post in question?
> […](#)
> On 6 Aug 2023, 23.37 +0300, JustDalek ***@***.***>, wrote: Hello! I dont know when the change happened, but some time ago I noticed my videos preview began to look a bit odd on my mastodon instance. Today I compared against mastodon.social and noticed it is very different My videos on the vanilla UI fills out a nice frame as seen here Whereas on my instance with birdUI, they seem to do this The biggest noticeable issue of course is the giant black bars that look gross. Is that something we can change? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Sure thing!

Here is my post
https://baka.social/@JustDalek_/110844523560255102

**Comment by ronilaukkarinen** [comment]
Mastodon.social runs nightly, like me. Your instance runs stable? That is the reason most probably.

Here's how it looks on my instance (newest nightly):

![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/d593179d-748f-409d-b5ad-1e73afd787a2)

Ultra accessible version:

![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/a8296160-7fff-4ee2-8e0c-b791e3a75872)

So which version are you using? Have you tried with default theme?

Mastodon Bird UI does not change aspect ratio and the improvements for video and other media came in Mastodon core, released [July 25](https://mastodon.social/@Gargron/110774797138668211), here's the [PR](https://github.com/mastodon/mastodon/pull/26132).
