### ISSUE TITLE
Display Boost and Favorite count 

### ISSUE THREAD

**Issue by mitexleo** [ronilaukkarinen/mastodon-bird-ui#80]
On my instance, the boost and favorites count isn't showing up in the home feed, even though I'm using the nightly version.

My instance (Buddyverse.xyz):
![SmartSelect_20230916-201259_Vivaldi Browser](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/114842102/3f82f859-ff7a-4c5e-acf1-43e787c419bd)

mementomori.social :
![SmartSelect_20230916-201210_Vivaldi Browser](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/114842102/65465388-3584-4f8c-a27b-fb0eab39863a)

**Comment by ronilaukkarinen** [comment]
This is not part of the Mastodon Bird UI. How could CSS style change any functionality? I have changed that to the fork of my instance. A Mastodon issue related to this can be found [here](https://github.com/mastodon/mastodon/issues/23058).
