### ISSUE TITLE
Interface doesn't switch to desktop mode on Pixel Fold inner screen.

### ISSUE THREAD

**Issue by Pixelle3D** [ronilaukkarinen/mastodon-bird-ui#83]
When you use this theme on a foldable like Pixel Fold it stretches the mobile UI instead of switching to desktop. Desktop view request from browser is also ignored. 
![Screenshot_20230920-144032](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/144811564/30afc054-fef3-44da-b4b9-067a0da09f81)

**Comment by ronilaukkarinen** [comment]
Doesn't look like a Mastodon Bird UI issue, please open an issue [here](https://github.com/mastodon/mastodon/issues).
