### ISSUE TITLE
Profile view on mobile leaves kebab menu out

### ISSUE THREAD

**Issue by ikke-t** [ronilaukkarinen/mastodon-bird-ui#87]
See how on mobile the profile'd kebab menu falls out and is not useable. Browser brave, android 13:

![Screenshot_2023-09-22-12-11-26-43_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1146409/fbf58a21-8eb9-45b8-a153-ebaf88ceee0c)
 
To get to menu I need to switch to horizontal mode. Perhaps css could make kebab align to right edge of screen?

**Comment by ronilaukkarinen** [comment]
Can you share the full screenshot?

**Comment by ikke-t** [comment]
Moi, that was the whole width. Here full
![Screenshot_2023-09-22-17-42-26-30_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1146409/cf785a26-6e33-4862-8ecf-5f97ea09df64)

**Comment by ronilaukkarinen** [comment]
Ahhh, I see. The first screenshot didn't seem that way. I think the only way is to truncate the text in mobile if it's too wide. I'll think about this.

**Comment by ikke-t** [comment]
Yes, no hurry, Ibjust thought to mention. The piece of the button works though.

**Comment by ronilaukkarinen** [comment]
For really small screens it has to be like this:

![ezgif com-video-to-gif (8)](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/cc3af887-bbdf-47db-a067-a8a3945cbb74)

**Comment by ikke-t** [comment]
I also reasoned so, looks good! BTW, I don't think this model is exceptionally small screen, OP11 is quite big. The Finnish translation just makes the unfollow button super long. If it was "Unohda" or some other shorter translation, we didn't have the issue.

**Comment by ronilaukkarinen** [comment]
> I also reasoned so, looks good! BTW, I don't think this model is exceptionally small screen, OP11 is quite big. The Finnish translation just makes the unfollow button super long. If it was "Unohda" or some other shorter translation, we didn't have the issue.

Most OnePlus's I've had have had at least 480px width and for those the button should fit :thinking:

**Comment by pbb72** [comment]
Please don't forget the people that need increased font size to compensate for bad eyesight. Depending on how implemented, this decreases the effective resolution of the screen.

**Comment by ronilaukkarinen** [comment]
@pbb72 It should only take account to the browser width. So zoom works as long as there's space. After all it's better accessibility to make the settings menu available rather than not, don't you think? Mastodon core also behaves this way.
