### ISSUE TITLE
Issue with Boost animation

### ISSUE THREAD

**Issue by mitexleo** [ronilaukkarinen/mastodon-bird-ui#88]
Hello Rolle,
Thank you so much for your efforts to improve mastodon experience. 
I encountered this issue while boosting posts:

https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/114842102/9515bfc1-18bb-45a5-8b10-6e6a525229ca

Thanks 😊

**Comment by ronilaukkarinen** [comment]
Fixed in 1.7.7.
