### ISSUE TITLE
Live feed icon missing when inactive

### ISSUE THREAD

**Issue by MikeHuntington** [ronilaukkarinen/mastodon-bird-ui#90]
Just started seeing this after updating to 1.7.7 - The Live Feeds icon seems to be missing. It shows up when you actually go to the Live Feeds page.

<img width="350" alt="Screenshot 2023-09-23 at 3 46 36 PM" src="https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/2466745/8c44a7ec-654c-49c2-beab-5bd1ca7dff01">

**Comment by ronilaukkarinen** [comment]
Does it still happen in 1.7.8rc3?

**Comment by MikeHuntington** [comment]
Still no luck after waiting for cache to clear and update. Going back to a previous version (before today's releases) it works. My instance is (https://neovibe.app) if you'd like to see.

**Comment by ronilaukkarinen** [comment]
@MikeHuntington Please try 1.7.8rc6.

**Comment by MikeHuntington** [comment]
All good now. Thank you!
