### ISSUE TITLE
Display name and username cutoffs when on mobile

### ISSUE THREAD

**Issue by JustDalek** [ronilaukkarinen/mastodon-bird-ui#93]
Greetings!. 

I wanted to ask if display names on mobile and usernames could have some review. 
Using mementomori.social for illustration

Using chrome mobile view with iPhone XR settings for easier screenshot and demo

<img width="247" alt="image" src="https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/78516780/6f18f942-62e4-4a30-b4b0-65c09fb24a67">

Ars technica shows 8 characters in the name, same with mastodon migration 
<img width="260" alt="image" src="https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/78516780/a83659c2-9d4c-4088-a086-f9e62a4c4f94">

But here we see these two accounts displaying more characters in the username

<img width="275" alt="image" src="https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/78516780/eab82a43-8609-4c8c-bb97-3374fbe7edfd">

Meanwhile the default mastodon layout seems to solve this by placing usernames above the username handle. 
I took this screenshot from their explore tab

![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/78516780/689d97e7-77d7-44ba-b7fb-daeb9fa1ec9a)

Thank you!

**Comment by ronilaukkarinen** [comment]
This is intentional and by design, directly from Twitter.

![Screen-Shot-2023-09-27-08-34-46 72](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/f7f2b961-3e3e-43eb-98c1-c26be375ae3a)

The layout wouldn't work otherwise. The usernames are just usually longer on Mastodon.
