### ISSUE TITLE
Performance regression between v1.6.0 and v1.7.8

### ISSUE THREAD

**Issue by Fell** [ronilaukkarinen/mastodon-bird-ui#96]
I updated from v1.6.0 to v1.7.8 and now my phone gets really hot while scrolling and battery life is noticeably worse. I reverted back to the stock Mastodon UI for a few weeks and the problem went away.

I think somewhere between v1.6.0 and v1.7.8 a massive inefficiency was introduced, forcing the browser to re-render parts of the screen more often than before.

I assumed it might be the blur effect, but that was already present in v1.6.0.

Do you have any ideas what that could be?

It will take me a lot of time to test every single release, because I have to use it for a few minutes to see if my device gets hot.

Google Pixel 4a
Android 13
Chrome 117

**Comment by ronilaukkarinen** [comment]
Hmm, I haven't encountered this. Since then I have added few more micro interactions that are all base64 and contain a lot of keyframes. You could try to remove all micro-interactions first and try again?

**Comment by Fell** [comment]
The problem appears to have gone away in v1.7.9 and Chrome 118. Maybe it was a very edge-casey Chrome bug.
