### ISSUE TITLE
Reply content slightly off and partly cropped

### ISSUE THREAD

**Issue by vinzv** [ronilaukkarinen/mastodon-bird-ui#97]
What the title says. I'm not sure if that's a bug or if I misconfigured?

![grafik](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/74432/f31bbfc4-d74e-4c73-9168-21fe484178a0)

**Comment by ronilaukkarinen** [comment]
What is your exact version of Mastodon and URL to your instance? Are you by any chance using old version of Mastodon? The latest version needs at least 4.2.0.

**Comment by vinzv** [comment]
Ah, sorry. My issue was written too briefly.

I'm running v4.2.0 stable (or atm v4.3.0-alpha to be accurate because of my Git messing) on https://noto.social.

Here's an example thread: https://noto.social/@vinzv/111201553045545241

**Comment by ronilaukkarinen** [comment]
> Here's an example thread: https://noto.social/@vinzv/111201553045545241

You are using very old Mastodon Bird UI version. The latest version is 1.8.0rc2: 2023-10-07.

![Screen-Shot-2023-10-10-17-34-34](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/0e798b74-1916-4ed3-a276-ad427a7619c2)

**Comment by vinzv** [comment]
Whoa... I have no idea how that could happen as I just used the commands from README.md.

Nevertheless, updating the files fixed it. Sorry for the noise and thank you for your time!

**Comment by ronilaukkarinen** [comment]
Oh yes it always needs to be `export MASTODON_VERSION_FOR_BIRD_UI="main"` because all the stable versions are obsolote. It is like that in the command itself in the README.md, just the comment was left there. Always use main. I'll update the README accordingly.

**Comment by vinzv** [comment]
Cool, thanks again! :hugs:
