### ISSUE TITLE
Certain browsers not respecting CSS

### ISSUE THREAD

**Issue by DismalShadowX** [ronilaukkarinen/mastodon-bird-ui#98]
Noticed an issue with Chrome and Edge or it's intended by design while playing around with CSS. Latest version of Chrome and Firefox on Windows and mobile, both caches cleared.

Chrome/Edge:

![Screenshot 2023-10-10 025801](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/24910097/12c92f7d-59ff-4fb4-85d7-5ef2632b3af3)

Firefox:

![Screenshot 2023-10-10 025853](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/24910097/8cdacc3e-b9d8-469c-a3e9-d8fa14c21d87)

Chrome:/Edge:

![Screenshot 2023-10-10 030047](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/24910097/79c80249-49c7-427c-bc66-856be39ab17b)

Firefox:

![Screenshot 2023-10-10 024832](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/24910097/030dc3f6-4eff-4402-9187-dfb862d760dd)

Not sure about other browsers like Safari, don't have it installed. I don't think applying CSS colors is the issue here, as you can see above images in both our case are showing green for verified and working as intended for **Firefox** only. Regression issue? If this is how Chromium browsers handles it, otherwise this can be closed.

**Comment by ronilaukkarinen** [comment]
This is known, [:has is not yet supported on Firefox](https://github.com/ronilaukkarinen/mastodon-bird-ui/issues/61#issuecomment-1718305865). There is no workaround so the fallback design is "good enough".
